- platform: github
  href: https://github.com/samiullaansari/
  label: GitHub
  title: GitHub
  class: social-github
- platform: linkedin
  href: https://www.linkedin.com/in/sami-iitb/
  label: LinkedIn
  title: LinkedIn
  class: social-linkedin
- platform: x
  href: https://x.com/sami_iitb/
  label: X
  title: X
  class: social-x
- platform: youtube
  href: https://www.youtube.com/@DeepPaceAI
  label: YouTube
  title: YouTube
  class: social-youtube
- platform: email
  href: mailto:samiullaansari567@gmail.com
  label: Email
  title: samiullaansari567@gmail.com
  class: social-email